apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  labels: 
    app: demo-voting-app
    name: demo-voting-pod
  
spec: 
  containers: 
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports: 
        - 
          containerPort: 80